test_configs:
  - maze_type: "maze"
    robot_shape: "pentagon"
    optimizer_type: "mpcc"
    dynamics_type: "differential_drive"
    path_planner: "astar"

  - maze_type: "oblique_maze"
    robot_shape: "triangle"
    optimizer_type: "mpcc"
    dynamics_type: "differential_drive"
    path_planner: "astar"

  - maze_type: "oblique_maze"
    robot_shape: "rectangle"
    optimizer_type: "mpcc"
    dynamics_type: "differential_drive"
    path_planner: "astar"

  - maze_type: "oblique_maze"
    robot_shape: "pentagon"
    optimizer_type: "mpcc"
    dynamics_type: "differential_drive"
    path_planner: "astar"

defaults:
  frame_skip: 3
  simulation_time: 60.0
  generate_animation: true
  generate_plots: true
  speed_range: [0.0, 0.30]
  clearance_range: [-0.08, 0.08]
  risk_range: [0.0, 0.035]
